# version: '3.8'
services:
  db:
    image: postgres:12.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5678:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    ports:
      - "5454:6789"
    depends_on:
      - db
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PRIVATE_KEY1: "x7edhuXGhd7ansd5mp9qEMwVpVoiemLY"
      PRIVATE_KEY2: "0cc27f41-be0"
      POSTGRES_HOST: db
      PORT: 6789

volumes:
  db_data: