CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE user_gender AS ENUM ('Male','Female','Non-binary','Other');
CREATE TYPE connection_status AS ENUM ('pending', 'accepted', 'blocked');


CREATE TABLE "user" (
  "id" uuid PRIMARY KEY DEFAULT (uuid_generate_v4()),
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "dob" timestamp NOT NULL,
  "mobile" varchar,
  "email" varchar UNIQUE NOT NULL,
  "username" varchar UNIQUE NOT NULL,
  "password_hash" varchar,
  "work_uploaded" integer DEFAULT 0,
  "work_done" integer DEFAULT 0,
  "work_score" integer DEFAULT 0,
  "total_work_score" integer DEFAULT 1,
  "bio" varchar,
  "profile_picture" varchar DEFAULT '',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "gender" user_gender NOT NULL,
  "links" varchar[]
);

CREATE TABLE "education" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "institution_name" varchar NOT NULL,
  "institution_city" varchar,
  "institution_country" varchar,
  "degree_or_course" varchar NOT NULL,
  "field_of_study" varchar,
  "degree_type" varchar,
  "start_date" timestamp NOT NULL,
  "graduation_date" timestamp,
  "grade_or_result" varchar,
  "honors" varchar
);

CREATE TABLE "connections" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "follower_id" uuid NOT NULL,
  "followed_id" uuid NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "status" connection_status DEFAULT 'pending'
);

CREATE UNIQUE INDEX ON "connections" ("follower_id", "followed_id");

ALTER TABLE "education" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "connections" ADD FOREIGN KEY ("follower_id") REFERENCES "user" ("id");

ALTER TABLE "connections" ADD FOREIGN KEY ("followed_id") REFERENCES "user" ("id");